### PR TITLE
replace Glorious Anthem with Spear of Heliod

### PR DESCRIPTION
**Pull request by davidchambers**
Spear of Heliod

### CODE REVIEW

**Comment by weakplayer** [comment]
interesting, i don't mind either, but this one dies to slightly more hate and costs more..

that said i like how its more playable in W+X aggro, nice thought :)

**Comment by Luggsie** [comment]
Doesn't cost more right?

**Comment by davidchambers** [comment]
They both cost `{1}{W}{W}`. Perhaps you're thinking of [Honor of the Pure](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=191058), @weakplayer?

**Comment by Luggsie** [comment]
More hate? Only downside is its legendary but that doesn't matter for cube.

**Comment by Luggsie** [comment]
Oh it's an arctic at and enchantment I see. 

Still probably better.

**Comment by davidchambers** [comment]
> Still probably better.

Spear has broader appeal. There are some decks which wouldn't play Anthem which might play Spear.

**Comment by weakplayer** [comment]
yeah i like the spear more man, and yeah was thinking of honour of the pure..

**Comment by weakplayer** [comment]
yeah i like the spear more man, and yeah was thinking of honour of the pure..

**Comment by Luggsie** [comment]
Just as I was saying I couldn't believe the depth of knowledge :p

**Pull request merged**
