### PR TITLE
replace Briarpack Alpha with Woodfall Primus

### PR DESCRIPTION
**Pull request by davidchambers**
Woodfall Primus

We need a few more cards to reward ramp decks.

### CODE REVIEW

**Comment by Luggsie** [comment]
Yep agree. 

What about primal Titan? Or would it mean we have to put all titans in?

Is fat enough and is on theme for more land tricks.

**Comment by davidchambers** [comment]
> What about primal Titan? [It's] fat enough and is on theme for more land tricks.

Let's consider adding Primeval Titan as well.

> Or would it mean we have to put all titans in?

I'm okay with playing just one card from a cycle.

**Comment by Luggsie** [comment]
Can we add hornet queen? 

Heavy green commitment is is funky and powerful.

**Comment by weakplayer** [comment]
keen on the queen regardless of natural order, but keen on both

**Pull request merged**
