### PR TITLE
replace Night Terrors with Hymn to Tourach

### PR DESCRIPTION
**Pull request by davidchambers**
Hymn to Tourach

### CODE REVIEW

**Comment by Luggsie** [comment]
Balance is the best discard spell in the game.

**Comment by davidchambers** [comment]
> Balance is the best discard spell in the game.

Absolutely. I seem to recall a turn one Balance, discard down to one, in a History of Magic event.

**Comment by weakplayer** [comment]
i'd really like to see tidehollow scullur and brain maggot included, but i do like drafting them lol

**Comment by weakplayer** [comment]
balance is so good vs green rampingtons

**Comment by davidchambers** [comment]
> i'd really like to see tidehollow scullur and brain maggot included

We should replace Gerrard's Verdict with Tidehollow Sculler.

Do you want to include Brain Maggot in addition to Mesmeric Fiend?

**Comment by Luggsie** [comment]
should be either or but to be honest it doesnt cut the mustard.

recursion decks probably want a thrull surgeon anyways - depends if we
favour grindy vs some disruption for other decks (including aggro)

TBH i dont thin it does enough in aggro/hybrid decks so either go surgeon
or remove for something else.... (read mind twist, rakdos return, or
skittering skurge or somehting

**Pull request merged**
